# -*- coding: utf-8 -*-
"""perceptron_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16AKlKUU8FR04y1GFnB-QWyqabnH6NqrU
"""

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/bipulshahi/Dataset/refs/heads/main/Advertising.csv',
                 index_col=0)
df.head()

X = df[['TV', 'radio' ,	'newspaper']]
y = df['sales']

#Yh = w0 + w1X1 + w2X2 + w3X3

w0 = 1
w1 = 1
w2 = 1
w3 = 1

Yh = w0 + w1*X.TV + w2*X.radio + w3*X.newspaper          #feed forward process
print(Yh)

error = ((y - Yh)**2).mean()
print(error)

#Cacluate gradient

#Tune the value of weights using gradients

#Calculte Yh and error to check if it reduced or not